import { AppSidebar } from "@/features/shared/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/features/shared/components/ui/sidebar";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { getLocale } from "next-intl/server";
import StoreProvider from "@/app/store-provider";
import { ATTRIBUTE_SLICE_NAME } from "@/features/attributes";
import { fetchAttributesListForSelect } from "@/app/actions/attribute";
import { CATEGORY_SLICE_NAME } from "@/features/categories/store/slice";
import { fetchCategoriesListForSelect } from "@/app/actions/category";
import { BRAND_SLICE_NAME } from "@/features/brands/store/slice";
import { fetchBrandsListForSelect } from "@/app/actions/brand";
import { SERIES_SLICE_NAME } from "@/features/series/store/slice";
import { fetchSeriesListForSelect } from "@/app/actions/series";
import { COLLECTION_SLICE_NAME } from "@/features/collections/store/slice";
import { fetchCollectionsListForSelect } from "@/app/actions/collection";
import { CHANNEL_SLICE_NAME } from "@/features/channels/store/slice";
import { fetchChannelsListForSelect } from "@/app/actions/channel";
import { CURRENCY_SLICE_NAME } from "@/features/currencies/store/slice";
import { fetchCurrenciesListForSelect } from "@/app/actions/currency";
import { MEDIA_COLLECTION_SLICE_NAME } from "@/features/media-collections/store/slice";
import { fetchMediaCollectionsListForSelect } from "@/app/actions/media-collection";
import { ACTIVE_CHANNEL_COOKIE } from "@/features/channels/constants";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The Redux store (with every *Select list preloaded) lives here, not in the
// root [locale] layout: everything under (private) is guaranteed
// authenticated by proxy.ts, but the root layout also wraps the public
// /auth/sign-in page, which must render even with no token yet - fetching
// these there would crash the sign-in page itself before login is possible.
export default async function PrivateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  // Read the sidebar's open/collapsed state and width from cookies on the
  // server, so the very first paint already matches what the user left it
  // at - without this, the sidebar visibly snaps to its default state/width
  // on every reload before the client-only effect corrects it.
  const defaultOpen = cookieStore.get("sidebar_state")?.value !== "false";
  const storedWidth = Number(cookieStore.get("sidebar_width")?.value);
  const defaultWidth = storedWidth || undefined;

  const locale = await getLocale();
  const channelsSelect = await fetchChannelsListForSelect({ locale });
  // No cookie yet (first visit) - land on the default channel rather than
  // "all channels", so a fresh session starts scoped somewhere sensible.
  // (Entity list pages use features/channels/get-active-channel-id.ts for
  // the same fallback, since they don't already have channelsSelect fetched.)
  const activeChannelId = Number(cookieStore.get(ACTIVE_CHANNEL_COOKIE)?.value)
    || channelsSelect.find(channel => channel.is_default)?.id
    || null;

  return (
    <StoreProvider preloadedState={{
      [ATTRIBUTE_SLICE_NAME]: {
        attributesSelect: await fetchAttributesListForSelect({ locale })
      },
      [CATEGORY_SLICE_NAME]: {
        categoriesSelect: await fetchCategoriesListForSelect({ locale })
      },
      [BRAND_SLICE_NAME]: {
        brandsSelect: await fetchBrandsListForSelect({ locale })
      },
      [SERIES_SLICE_NAME]: {
        seriesSelect: await fetchSeriesListForSelect({ locale })
      },
      [COLLECTION_SLICE_NAME]: {
        collectionsSelect: await fetchCollectionsListForSelect({ locale })
      },
      [CHANNEL_SLICE_NAME]: {
        channelsSelect,
        activeChannelId
      },
      [CURRENCY_SLICE_NAME]: {
        currenciesSelect: await fetchCurrenciesListForSelect({ locale })
      },
      [MEDIA_COLLECTION_SLICE_NAME]: {
        mediaCollectionsSelect: await fetchMediaCollectionsListForSelect({ locale })
      }
    }}>
      <SidebarProvider defaultOpen={defaultOpen} defaultWidth={defaultWidth}>
        <AppSidebar />
        <main className="w-full flex flex-col flex-1 min-w-0">
          <header className="flex h-14 shrink-0 items-center border-b px-4">
            <SidebarTrigger />
          </header>
          <div className="flex flex-1 flex-col gap-6 p-6">
            {children}
          </div>
        </main>
      </SidebarProvider>
    </StoreProvider>
  );
}
