import { AppSidebar } from "@/features/shared/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/features/shared/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PrivateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="w-full flex flex-col flex-1 min-w-0">
        <header className="flex h-14 shrink-0 items-center border-b px-4">
          <SidebarTrigger />
        </header>
        <div className="flex flex-1 flex-col gap-6 p-6">
          {children}
        </div>
      </main>
    </SidebarProvider>
  );
}
