import { AppSidebar } from "@/features/shared/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/features/shared/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PrivateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="w-full flex flex-col flex-1">
        <SidebarTrigger />
        <div className="p-6 flex flex-col flex-1">
          {children}
        </div>
      </main>
    </SidebarProvider>
  );
}
