import type { Metadata } from "next";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { TooltipProvider } from "@/features/shared/components/ui/tooltip";
import StoreProvider from "../store-provider";
import { ATTRIBUTE_SLICE_NAME } from "@/features/attributes";
import { fetchAttributesListForSelect } from "../actions/attribute";
import { getLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider>
          <StoreProvider preloadedState={{ 
            [ATTRIBUTE_SLICE_NAME]: {
              attributesSelect: await fetchAttributesListForSelect({ locale })
            }
           }}>
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
