import type { Metadata } from "next";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import StoreProvider from "../store-provider";
import { TooltipProvider } from "@/features/shared/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextIntlClientProvider>
          <StoreProvider>
            <TooltipProvider>
              {children}
            </TooltipProvider>
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
